apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geotrack

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: geotrack-platform
  app.kubernetes.io/managed-by: kustomize
